package com.e3expo.e3.model;

import java.io.Serializable;
public class AppealLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_appeal_log.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_appeal_log.appeal_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer appealId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_appeal_log.handler_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer handlerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_appeal_log.handler_remark
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String handlerRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_appeal_log.status
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_appeal_log.change_designer
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer changeDesigner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_appeal_log.result
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_appeal_log.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_appeal_log.id
     *
     * @return the value of te_appeal_log.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_appeal_log.id
     *
     * @param id the value for te_appeal_log.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_appeal_log.appeal_id
     *
     * @return the value of te_appeal_log.appeal_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getAppealId() {
        return appealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_appeal_log.appeal_id
     *
     * @param appealId the value for te_appeal_log.appeal_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setAppealId(Integer appealId) {
        this.appealId = appealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_appeal_log.handler_id
     *
     * @return the value of te_appeal_log.handler_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getHandlerId() {
        return handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_appeal_log.handler_id
     *
     * @param handlerId the value for te_appeal_log.handler_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setHandlerId(Integer handlerId) {
        this.handlerId = handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_appeal_log.handler_remark
     *
     * @return the value of te_appeal_log.handler_remark
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getHandlerRemark() {
        return handlerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_appeal_log.handler_remark
     *
     * @param handlerRemark the value for te_appeal_log.handler_remark
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setHandlerRemark(String handlerRemark) {
        this.handlerRemark = handlerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_appeal_log.status
     *
     * @return the value of te_appeal_log.status
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_appeal_log.status
     *
     * @param status the value for te_appeal_log.status
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_appeal_log.change_designer
     *
     * @return the value of te_appeal_log.change_designer
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getChangeDesigner() {
        return changeDesigner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_appeal_log.change_designer
     *
     * @param changeDesigner the value for te_appeal_log.change_designer
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setChangeDesigner(Integer changeDesigner) {
        this.changeDesigner = changeDesigner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_appeal_log.result
     *
     * @return the value of te_appeal_log.result
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_appeal_log.result
     *
     * @param result the value for te_appeal_log.result
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_appeal_log.create_time
     *
     * @return the value of te_appeal_log.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_appeal_log.create_time
     *
     * @param createTime the value for te_appeal_log.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}