package com.e3expo.e3.model;

import java.io.Serializable;
public class Bank implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_bank.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_bank.bank_name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_bank.bank_branch_name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String bankBranchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_bank.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_bank.id
     *
     * @return the value of dic_bank.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_bank.id
     *
     * @param id the value for dic_bank.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_bank.bank_name
     *
     * @return the value of dic_bank.bank_name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_bank.bank_name
     *
     * @param bankName the value for dic_bank.bank_name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_bank.bank_branch_name
     *
     * @return the value of dic_bank.bank_branch_name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getBankBranchName() {
        return bankBranchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_bank.bank_branch_name
     *
     * @param bankBranchName the value for dic_bank.bank_branch_name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setBankBranchName(String bankBranchName) {
        this.bankBranchName = bankBranchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_bank.is_valid
     *
     * @return the value of dic_bank.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_bank.is_valid
     *
     * @param isValid the value for dic_bank.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}