package com.e3expo.e3.model;

import java.io.Serializable;
public class CompanyConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_company_config.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_company_config.order_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_company_config.rebate
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Float rebate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_company_config.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_company_config.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_company_config.id
     *
     * @return the value of te_company_config.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_company_config.id
     *
     * @param id the value for te_company_config.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_company_config.order_num
     *
     * @return the value of te_company_config.order_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_company_config.order_num
     *
     * @param orderNum the value for te_company_config.order_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_company_config.rebate
     *
     * @return the value of te_company_config.rebate
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Float getRebate() {
        return rebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_company_config.rebate
     *
     * @param rebate the value for te_company_config.rebate
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setRebate(Float rebate) {
        this.rebate = rebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_company_config.is_valid
     *
     * @return the value of te_company_config.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_company_config.is_valid
     *
     * @param isValid the value for te_company_config.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_company_config.create_time
     *
     * @return the value of te_company_config.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_company_config.create_time
     *
     * @param createTime the value for te_company_config.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}