package com.e3expo.e3.model;

import java.io.Serializable;
public class CompanyConfigLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_company_config_log.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_company_config_log.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_company_config_log.message
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_company_config_log.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_company_config_log.id
     *
     * @return the value of te_company_config_log.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_company_config_log.id
     *
     * @param id the value for te_company_config_log.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_company_config_log.user_id
     *
     * @return the value of te_company_config_log.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_company_config_log.user_id
     *
     * @param userId the value for te_company_config_log.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_company_config_log.message
     *
     * @return the value of te_company_config_log.message
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_company_config_log.message
     *
     * @param message the value for te_company_config_log.message
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_company_config_log.create_time
     *
     * @return the value of te_company_config_log.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_company_config_log.create_time
     *
     * @param createTime the value for te_company_config_log.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}