package com.e3expo.e3.model;

import java.io.Serializable;

public class DesignerOrder implements Serializable {

    private Integer id;


    private Integer orderId;


    private Integer designerId;


    private String designerName;


    private String designerType;

    private String designerLevel;

    private String designerPhone;

    private String designQq;


    private Integer isValid;

    private Integer pid;

    private Integer auditStatus;

    private Integer isLock;

    private String nodeId;

    private Long createTime;

    private Long updateTime;

    public DesignerOrder() {
    }

    public DesignerOrder(Integer orderId, Integer designerId) {
        this.orderId = orderId;
        this.designerId = designerId;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Integer getDesignerId() {
        return designerId;
    }


    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_order.designer_id
     *
     * @param designerId the value for te_designer_order.designer_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setDesignerId(Integer designerId) {
        this.designerId = designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_order.designer_name
     *
     * @return the value of te_designer_order.designer_name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getDesignerName() {
        return designerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_order.designer_name
     *
     * @param designerName the value for te_designer_order.designer_name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setDesignerName(String designerName) {
        this.designerName = designerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_order.designer_type
     *
     * @return the value of te_designer_order.designer_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getDesignerType() {
        return designerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_order.designer_type
     *
     * @param designerType the value for te_designer_order.designer_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setDesignerType(String designerType) {
        this.designerType = designerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_order.designer_level
     *
     * @return the value of te_designer_order.designer_level
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getDesignerLevel() {
        return designerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_order.designer_level
     *
     * @param designerLevel the value for te_designer_order.designer_level
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setDesignerLevel(String designerLevel) {
        this.designerLevel = designerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_order.designer_phone
     *
     * @return the value of te_designer_order.designer_phone
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getDesignerPhone() {
        return designerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_order.designer_phone
     *
     * @param designerPhone the value for te_designer_order.designer_phone
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setDesignerPhone(String designerPhone) {
        this.designerPhone = designerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_order.design_qq
     *
     * @return the value of te_designer_order.design_qq
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getDesignQq() {
        return designQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_order.design_qq
     *
     * @param designQq the value for te_designer_order.design_qq
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setDesignQq(String designQq) {
        this.designQq = designQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_order.is_valid
     *
     * @return the value of te_designer_order.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_order.is_valid
     *
     * @param isValid the value for te_designer_order.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_order.pid
     *
     * @return the value of te_designer_order.pid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_order.pid
     *
     * @param pid the value for te_designer_order.pid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_order.audit_status
     *
     * @return the value of te_designer_order.audit_status
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_order.audit_status
     *
     * @param auditStatus the value for te_designer_order.audit_status
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_order.is_lock
     *
     * @return the value of te_designer_order.is_lock
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_order.is_lock
     *
     * @param isLock the value for te_designer_order.is_lock
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setIsLock(Integer isLock) {
        this.isLock = isLock;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_order.create_time
     *
     * @return the value of te_designer_order.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_order.create_time
     *
     * @param createTime the value for te_designer_order.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_order.update_time
     *
     * @return the value of te_designer_order.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_order.update_time
     *
     * @param updateTime the value for te_designer_order.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}