package com.e3expo.e3.model;

import java.io.Serializable;

import org.apache.ibatis.type.Alias;
@Alias("designerConfig")
public class DesignerConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_designer_config.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_designer_config.level
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_designer_config.name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_designer_config.type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_designer_config.price
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_designer_config.total_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer totalNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_designer_config.id
     *
     * @return the value of dic_designer_config.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_designer_config.id
     *
     * @param id the value for dic_designer_config.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_designer_config.level
     *
     * @return the value of dic_designer_config.level
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_designer_config.level
     *
     * @param level the value for dic_designer_config.level
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_designer_config.name
     *
     * @return the value of dic_designer_config.name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_designer_config.name
     *
     * @param name the value for dic_designer_config.name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_designer_config.type
     *
     * @return the value of dic_designer_config.type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_designer_config.type
     *
     * @param type the value for dic_designer_config.type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_designer_config.price
     *
     * @return the value of dic_designer_config.price
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_designer_config.price
     *
     * @param price the value for dic_designer_config.price
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_designer_config.total_num
     *
     * @return the value of dic_designer_config.total_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_designer_config.total_num
     *
     * @param totalNum the value for dic_designer_config.total_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }
}