package com.e3expo.e3.model;

import java.io.Serializable;
public class DesignerNeed implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_designer_need.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_designer_need.rfp_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer rfpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_designer_need.designer_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer designerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_designer_need.first_design_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer firstDesignNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_designer_need.detailed_design_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer detailedDesignNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_designer_need.work_file_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer workFileNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_designer_need.first_design_price
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Float firstDesignPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_designer_need.detailed_design_price
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Float detailedDesignPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_designer_need.work_file_price
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Float workFilePrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_need.id
     *
     * @return the value of te_designer_need.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_need.id
     *
     * @param id the value for te_designer_need.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_need.rfp_id
     *
     * @return the value of te_designer_need.rfp_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getRfpId() {
        return rfpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_need.rfp_id
     *
     * @param rfpId the value for te_designer_need.rfp_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setRfpId(Integer rfpId) {
        this.rfpId = rfpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_need.designer_type
     *
     * @return the value of te_designer_need.designer_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getDesignerType() {
        return designerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_need.designer_type
     *
     * @param designerType the value for te_designer_need.designer_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setDesignerType(Integer designerType) {
        this.designerType = designerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_need.first_design_num
     *
     * @return the value of te_designer_need.first_design_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getFirstDesignNum() {
        return firstDesignNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_need.first_design_num
     *
     * @param firstDesignNum the value for te_designer_need.first_design_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setFirstDesignNum(Integer firstDesignNum) {
        this.firstDesignNum = firstDesignNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_need.detailed_design_num
     *
     * @return the value of te_designer_need.detailed_design_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getDetailedDesignNum() {
        return detailedDesignNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_need.detailed_design_num
     *
     * @param detailedDesignNum the value for te_designer_need.detailed_design_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setDetailedDesignNum(Integer detailedDesignNum) {
        this.detailedDesignNum = detailedDesignNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_need.work_file_num
     *
     * @return the value of te_designer_need.work_file_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getWorkFileNum() {
        return workFileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_need.work_file_num
     *
     * @param workFileNum the value for te_designer_need.work_file_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setWorkFileNum(Integer workFileNum) {
        this.workFileNum = workFileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_need.first_design_price
     *
     * @return the value of te_designer_need.first_design_price
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Float getFirstDesignPrice() {
        return firstDesignPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_need.first_design_price
     *
     * @param firstDesignPrice the value for te_designer_need.first_design_price
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setFirstDesignPrice(Float firstDesignPrice) {
        this.firstDesignPrice = firstDesignPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_need.detailed_design_price
     *
     * @return the value of te_designer_need.detailed_design_price
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Float getDetailedDesignPrice() {
        return detailedDesignPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_need.detailed_design_price
     *
     * @param detailedDesignPrice the value for te_designer_need.detailed_design_price
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setDetailedDesignPrice(Float detailedDesignPrice) {
        this.detailedDesignPrice = detailedDesignPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_need.work_file_price
     *
     * @return the value of te_designer_need.work_file_price
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Float getWorkFilePrice() {
        return workFilePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_need.work_file_price
     *
     * @param workFilePrice the value for te_designer_need.work_file_price
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setWorkFilePrice(Float workFilePrice) {
        this.workFilePrice = workFilePrice;
    }
}