package com.e3expo.e3.model;

import java.io.Serializable;
public class Function implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_function.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_function.name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_function.pid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_function.id
     *
     * @return the value of te_function.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_function.id
     *
     * @param id the value for te_function.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_function.name
     *
     * @return the value of te_function.name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_function.name
     *
     * @param name the value for te_function.name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_function.pid
     *
     * @return the value of te_function.pid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_function.pid
     *
     * @param pid the value for te_function.pid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}