package com.e3expo.e3.model;

import java.io.Serializable;
public class Invoice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_invoice.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_invoice.invoice_title
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String invoiceTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_invoice.code_issuer
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String codeIssuer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_invoice.address
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_invoice.addressee
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String addressee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_invoice.phone
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_invoice.rfp_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer rfpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_invoice.status
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_invoice.express_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer expressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_invoice.express_no
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String expressNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_invoice.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_invoice.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_invoice.id
     *
     * @return the value of te_invoice.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_invoice.id
     *
     * @param id the value for te_invoice.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_invoice.invoice_title
     *
     * @return the value of te_invoice.invoice_title
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_invoice.invoice_title
     *
     * @param invoiceTitle the value for te_invoice.invoice_title
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_invoice.code_issuer
     *
     * @return the value of te_invoice.code_issuer
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getCodeIssuer() {
        return codeIssuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_invoice.code_issuer
     *
     * @param codeIssuer the value for te_invoice.code_issuer
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setCodeIssuer(String codeIssuer) {
        this.codeIssuer = codeIssuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_invoice.address
     *
     * @return the value of te_invoice.address
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_invoice.address
     *
     * @param address the value for te_invoice.address
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_invoice.addressee
     *
     * @return the value of te_invoice.addressee
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getAddressee() {
        return addressee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_invoice.addressee
     *
     * @param addressee the value for te_invoice.addressee
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setAddressee(String addressee) {
        this.addressee = addressee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_invoice.phone
     *
     * @return the value of te_invoice.phone
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_invoice.phone
     *
     * @param phone the value for te_invoice.phone
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_invoice.rfp_id
     *
     * @return the value of te_invoice.rfp_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getRfpId() {
        return rfpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_invoice.rfp_id
     *
     * @param rfpId the value for te_invoice.rfp_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setRfpId(Integer rfpId) {
        this.rfpId = rfpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_invoice.status
     *
     * @return the value of te_invoice.status
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_invoice.status
     *
     * @param status the value for te_invoice.status
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_invoice.express_id
     *
     * @return the value of te_invoice.express_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getExpressId() {
        return expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_invoice.express_id
     *
     * @param expressId the value for te_invoice.express_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setExpressId(Integer expressId) {
        this.expressId = expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_invoice.express_no
     *
     * @return the value of te_invoice.express_no
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getExpressNo() {
        return expressNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_invoice.express_no
     *
     * @param expressNo the value for te_invoice.express_no
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setExpressNo(String expressNo) {
        this.expressNo = expressNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_invoice.create_time
     *
     * @return the value of te_invoice.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_invoice.create_time
     *
     * @param createTime the value for te_invoice.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_invoice.update_time
     *
     * @return the value of te_invoice.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_invoice.update_time
     *
     * @param updateTime the value for te_invoice.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}