package com.e3expo.e3.model;

public class Material {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_material.id
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_material.name
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_material.id
     *
     * @return the value of dic_material.id
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_material.id
     *
     * @param id the value for dic_material.id
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_material.name
     *
     * @return the value of dic_material.name
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_material.name
     *
     * @param name the value for dic_material.name
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}