package com.e3expo.e3.model;

import java.io.Serializable;

import org.apache.ibatis.type.Alias;
import org.hibernate.validator.constraints.NotBlank;@Alias("osUser")
public class OsUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_os_user.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_os_user.name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_os_user.mobile
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    @NotBlank(message ="手机必填")
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_os_user.password
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    @NotBlank(message ="密码必填")
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_os_user.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_os_user.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_os_user.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_os_user.user_no
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String userNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_os_user.id
     *
     * @return the value of te_os_user.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_os_user.id
     *
     * @param id the value for te_os_user.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_os_user.name
     *
     * @return the value of te_os_user.name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_os_user.name
     *
     * @param name the value for te_os_user.name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_os_user.mobile
     *
     * @return the value of te_os_user.mobile
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_os_user.mobile
     *
     * @param mobile the value for te_os_user.mobile
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_os_user.password
     *
     * @return the value of te_os_user.password
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_os_user.password
     *
     * @param password the value for te_os_user.password
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_os_user.is_valid
     *
     * @return the value of te_os_user.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_os_user.is_valid
     *
     * @param isValid the value for te_os_user.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_os_user.create_time
     *
     * @return the value of te_os_user.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_os_user.create_time
     *
     * @param createTime the value for te_os_user.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_os_user.update_time
     *
     * @return the value of te_os_user.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_os_user.update_time
     *
     * @param updateTime the value for te_os_user.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_os_user.user_no
     *
     * @return the value of te_os_user.user_no
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_os_user.user_no
     *
     * @param userNo the value for te_os_user.user_no
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }
}