package com.e3expo.e3.model;

import java.io.Serializable;
public class Payment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.payee
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String payee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.receivables_company
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String receivablesCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.bank_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.receivables_account
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String receivablesAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.amount
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.pay_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.status
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.order_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.node_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer nodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.remark
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment.serial_no
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String serialNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.id
     *
     * @return the value of te_payment.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.id
     *
     * @param id the value for te_payment.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.payee
     *
     * @return the value of te_payment.payee
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getPayee() {
        return payee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.payee
     *
     * @param payee the value for te_payment.payee
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setPayee(String payee) {
        this.payee = payee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.receivables_company
     *
     * @return the value of te_payment.receivables_company
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getReceivablesCompany() {
        return receivablesCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.receivables_company
     *
     * @param receivablesCompany the value for te_payment.receivables_company
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setReceivablesCompany(String receivablesCompany) {
        this.receivablesCompany = receivablesCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.bank_id
     *
     * @return the value of te_payment.bank_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.bank_id
     *
     * @param bankId the value for te_payment.bank_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.receivables_account
     *
     * @return the value of te_payment.receivables_account
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getReceivablesAccount() {
        return receivablesAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.receivables_account
     *
     * @param receivablesAccount the value for te_payment.receivables_account
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setReceivablesAccount(String receivablesAccount) {
        this.receivablesAccount = receivablesAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.amount
     *
     * @return the value of te_payment.amount
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.amount
     *
     * @param amount the value for te_payment.amount
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.pay_type
     *
     * @return the value of te_payment.pay_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.pay_type
     *
     * @param payType the value for te_payment.pay_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.user_id
     *
     * @return the value of te_payment.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.user_id
     *
     * @param userId the value for te_payment.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.status
     *
     * @return the value of te_payment.status
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.status
     *
     * @param status the value for te_payment.status
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.order_id
     *
     * @return the value of te_payment.order_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.order_id
     *
     * @param orderId the value for te_payment.order_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.node_id
     *
     * @return the value of te_payment.node_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.node_id
     *
     * @param nodeId the value for te_payment.node_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.remark
     *
     * @return the value of te_payment.remark
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.remark
     *
     * @param remark the value for te_payment.remark
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.create_time
     *
     * @return the value of te_payment.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.create_time
     *
     * @param createTime the value for te_payment.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.update_time
     *
     * @return the value of te_payment.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.update_time
     *
     * @param updateTime the value for te_payment.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment.serial_no
     *
     * @return the value of te_payment.serial_no
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment.serial_no
     *
     * @param serialNo the value for te_payment.serial_no
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }
}