package com.e3expo.e3.model;

import java.io.Serializable;
public class PaymentTimerConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment_timer_config.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment_timer_config.first_design_pay
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long firstDesignPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment_timer_config.detailed_design_pay
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long detailedDesignPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment_timer_config.work_file_pay
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long workFilePay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment_timer_config.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment_timer_config.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment_timer_config.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_payment_timer_config.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment_timer_config.id
     *
     * @return the value of te_payment_timer_config.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment_timer_config.id
     *
     * @param id the value for te_payment_timer_config.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment_timer_config.first_design_pay
     *
     * @return the value of te_payment_timer_config.first_design_pay
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getFirstDesignPay() {
        return firstDesignPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment_timer_config.first_design_pay
     *
     * @param firstDesignPay the value for te_payment_timer_config.first_design_pay
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setFirstDesignPay(Long firstDesignPay) {
        this.firstDesignPay = firstDesignPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment_timer_config.detailed_design_pay
     *
     * @return the value of te_payment_timer_config.detailed_design_pay
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getDetailedDesignPay() {
        return detailedDesignPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment_timer_config.detailed_design_pay
     *
     * @param detailedDesignPay the value for te_payment_timer_config.detailed_design_pay
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setDetailedDesignPay(Long detailedDesignPay) {
        this.detailedDesignPay = detailedDesignPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment_timer_config.work_file_pay
     *
     * @return the value of te_payment_timer_config.work_file_pay
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getWorkFilePay() {
        return workFilePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment_timer_config.work_file_pay
     *
     * @param workFilePay the value for te_payment_timer_config.work_file_pay
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setWorkFilePay(Long workFilePay) {
        this.workFilePay = workFilePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment_timer_config.user_id
     *
     * @return the value of te_payment_timer_config.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment_timer_config.user_id
     *
     * @param userId the value for te_payment_timer_config.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment_timer_config.is_valid
     *
     * @return the value of te_payment_timer_config.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment_timer_config.is_valid
     *
     * @param isValid the value for te_payment_timer_config.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment_timer_config.create_time
     *
     * @return the value of te_payment_timer_config.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment_timer_config.create_time
     *
     * @param createTime the value for te_payment_timer_config.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_payment_timer_config.update_time
     *
     * @return the value of te_payment_timer_config.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_payment_timer_config.update_time
     *
     * @param updateTime the value for te_payment_timer_config.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}