package com.e3expo.e3.model;

import java.io.Serializable;
public class Receivables implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_receivables.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_receivables.payee
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String payee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_receivables.pay_company
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String payCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_receivables.bank_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_receivables.pay_account
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String payAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_receivables.amount
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_receivables.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_receivables.status
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_receivables.order_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_receivables.node_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer nodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_receivables.remark
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_receivables.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_receivables. update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_receivables.serial_no
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String serialNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_receivables.id
     *
     * @return the value of te_receivables.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_receivables.id
     *
     * @param id the value for te_receivables.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_receivables.payee
     *
     * @return the value of te_receivables.payee
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getPayee() {
        return payee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_receivables.payee
     *
     * @param payee the value for te_receivables.payee
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setPayee(String payee) {
        this.payee = payee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_receivables.pay_company
     *
     * @return the value of te_receivables.pay_company
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getPayCompany() {
        return payCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_receivables.pay_company
     *
     * @param payCompany the value for te_receivables.pay_company
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setPayCompany(String payCompany) {
        this.payCompany = payCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_receivables.bank_id
     *
     * @return the value of te_receivables.bank_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_receivables.bank_id
     *
     * @param bankId the value for te_receivables.bank_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_receivables.pay_account
     *
     * @return the value of te_receivables.pay_account
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getPayAccount() {
        return payAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_receivables.pay_account
     *
     * @param payAccount the value for te_receivables.pay_account
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setPayAccount(String payAccount) {
        this.payAccount = payAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_receivables.amount
     *
     * @return the value of te_receivables.amount
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_receivables.amount
     *
     * @param amount the value for te_receivables.amount
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_receivables.user_id
     *
     * @return the value of te_receivables.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_receivables.user_id
     *
     * @param userId the value for te_receivables.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_receivables.status
     *
     * @return the value of te_receivables.status
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_receivables.status
     *
     * @param status the value for te_receivables.status
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_receivables.order_id
     *
     * @return the value of te_receivables.order_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_receivables.order_id
     *
     * @param orderId the value for te_receivables.order_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_receivables.node_id
     *
     * @return the value of te_receivables.node_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_receivables.node_id
     *
     * @param nodeId the value for te_receivables.node_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_receivables.remark
     *
     * @return the value of te_receivables.remark
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_receivables.remark
     *
     * @param remark the value for te_receivables.remark
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_receivables.create_time
     *
     * @return the value of te_receivables.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_receivables.create_time
     *
     * @param createTime the value for te_receivables.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_receivables. update_time
     *
     * @return the value of te_receivables. update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_receivables. update_time
     *
     * @param updateTime the value for te_receivables. update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_receivables.serial_no
     *
     * @return the value of te_receivables.serial_no
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_receivables.serial_no
     *
     * @param serialNo the value for te_receivables.serial_no
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }
}