package com.e3expo.e3.model;

import java.io.Serializable;
public class RoleFunction implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_function.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_function.role_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_function.function_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer functionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_function.id
     *
     * @return the value of tr_role_function.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_function.id
     *
     * @param id the value for tr_role_function.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_function.role_id
     *
     * @return the value of tr_role_function.role_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_function.role_id
     *
     * @param roleId the value for tr_role_function.role_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_function.function_id
     *
     * @return the value of tr_role_function.function_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_function.function_id
     *
     * @param functionId the value for tr_role_function.function_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }
}