package com.e3expo.e3.model;

import java.io.Serializable;

import org.apache.ibatis.type.Alias;
@Alias("singleTimerConfig")
public class SingleTimerConfig implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1248031445209253717L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_single_timer_config.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
	
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_single_timer_config.first_time_limit
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer firstTimeLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_single_timer_config.second_time_limit
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer secondTimeLimit;
    
    private Integer endTimeLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_single_timer_config.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_single_timer_config.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_single_timer_config.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_single_timer_config.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_single_timer_config.id
     *
     * @return the value of te_single_timer_config.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_single_timer_config.id
     *
     * @param id the value for te_single_timer_config.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_single_timer_config.first_time_limit
     *
     * @return the value of te_single_timer_config.first_time_limit
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getFirstTimeLimit() {
        return firstTimeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_single_timer_config.first_time_limit
     *
     * @param firstTimeLimit the value for te_single_timer_config.first_time_limit
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setFirstTimeLimit(Integer firstTimeLimit) {
        this.firstTimeLimit = firstTimeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_single_timer_config.second_time_limit
     *
     * @return the value of te_single_timer_config.second_time_limit
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getSecondTimeLimit() {
        return secondTimeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_single_timer_config.second_time_limit
     *
     * @param secondTimeLimit the value for te_single_timer_config.second_time_limit
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setSecondTimeLimit(Integer secondTimeLimit) {
        this.secondTimeLimit = secondTimeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_single_timer_config.user_id
     *
     * @return the value of te_single_timer_config.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_single_timer_config.user_id
     *
     * @param userId the value for te_single_timer_config.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_single_timer_config.is_valid
     *
     * @return the value of te_single_timer_config.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_single_timer_config.is_valid
     *
     * @param isValid the value for te_single_timer_config.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_single_timer_config.create_time
     *
     * @return the value of te_single_timer_config.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_single_timer_config.create_time
     *
     * @param createTime the value for te_single_timer_config.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_single_timer_config.update_time
     *
     * @return the value of te_single_timer_config.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_single_timer_config.update_time
     *
     * @param updateTime the value for te_single_timer_config.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

	public Integer getEndTimeLimit() {
		return endTimeLimit;
	}

	public void setEndTimeLimit(Integer endTimeLimit) {
		this.endTimeLimit = endTimeLimit;
	}
    
    
}