package com.e3expo.e3.model;

import java.io.Serializable;

public class UploadFile implements Serializable {

    private Integer id;

    private Integer fileType;

    private String filePath;

    private String nodeId;

    private Integer userId;

    private Integer orderId;

    private Integer isValid;

    private Integer uploadId;

    private Long createTime;

    private Integer planNum;

    public UploadFile() {
    }

    public UploadFile(Integer fileType, String filePath, Integer userId, Integer orderId) {
        this.fileType = fileType;
        this.filePath = filePath;
        this.userId = userId;
        this.orderId = orderId;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getFileType() {
        return fileType;
    }

    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_upload_file.file_path
     *
     * @param filePath the value for te_upload_file.file_path
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_upload_file.user_id
     *
     * @return the value of te_upload_file.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_upload_file.user_id
     *
     * @param userId the value for te_upload_file.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_upload_file.order_id
     *
     * @return the value of te_upload_file.order_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_upload_file.order_id
     *
     * @param orderId the value for te_upload_file.order_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_upload_file.is_valid
     *
     * @return the value of te_upload_file.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_upload_file.is_valid
     *
     * @param isValid the value for te_upload_file.is_valid
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_upload_file.upload_id
     *
     * @return the value of te_upload_file.upload_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getUploadId() {
        return uploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_upload_file.upload_id
     *
     * @param uploadId the value for te_upload_file.upload_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUploadId(Integer uploadId) {
        this.uploadId = uploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_upload_file.create_time
     *
     * @return the value of te_upload_file.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_upload_file.create_time
     *
     * @param createTime the value for te_upload_file.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_upload_file.plan_num
     *
     * @return the value of te_upload_file.plan_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getPlanNum() {
        return planNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_upload_file.plan_num
     *
     * @param planNum the value for te_upload_file.plan_num
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setPlanNum(Integer planNum) {
        this.planNum = planNum;
    }
}