package com.e3expo.e3.model;

import org.apache.ibatis.type.Alias;

import java.io.Serializable;

//@Alias("designerImage,userInfoFile")
@Alias("userInfoFile")
public class UserInfoFile implements Serializable {
    public UserInfoFile() {
    }

	public UserInfoFile(String fileName, String filePath, Integer fileType) {
        this.fileName = fileName;
        this.filePath = filePath;
        this.fileType = fileType;
    }

    private Integer id;


    private String fileName;

    private String filePath;

    private Integer fileType;

    private Integer userId;


    private Long createTime;

    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_image.id
     *
     * @return the value of te_designer_image.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_image.id
     *
     * @param id the value for te_designer_image.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_image.file_name
     *
     * @return the value of te_designer_image.file_name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_image.file_name
     *
     * @param fileName the value for te_designer_image.file_name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_image.file_path
     *
     * @return the value of te_designer_image.file_path
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_image.file_path
     *
     * @param filePath the value for te_designer_image.file_path
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_image.file_type
     *
     * @return the value of te_designer_image.file_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_image.file_type
     *
     * @param fileType the value for te_designer_image.file_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_image.user_id
     *
     * @return the value of te_designer_image.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_image.user_id
     *
     * @param userId the value for te_designer_image.user_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_image.create_time
     *
     * @return the value of te_designer_image.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_image.create_time
     *
     * @param createTime the value for te_designer_image.create_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_designer_image.update_time
     *
     * @return the value of te_designer_image.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_designer_image.update_time
     *
     * @param updateTime the value for te_designer_image.update_time
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}