package com.e3expo.e3.model;

import java.io.Serializable;
public class UserBank implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_bank.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_bank.bank_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private Integer bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_bank.bank_account
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_user_bank.bank_user_name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    private String bankUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_bank.id
     *
     * @return the value of tr_user_bank.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_bank.id
     *
     * @param id the value for tr_user_bank.id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_bank.bank_id
     *
     * @return the value of tr_user_bank.bank_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_bank.bank_id
     *
     * @param bankId the value for tr_user_bank.bank_id
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_bank.bank_account
     *
     * @return the value of tr_user_bank.bank_account
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_bank.bank_account
     *
     * @param bankAccount the value for tr_user_bank.bank_account
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_user_bank.bank_user_name
     *
     * @return the value of tr_user_bank.bank_user_name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public String getBankUserName() {
        return bankUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_user_bank.bank_user_name
     *
     * @param bankUserName the value for tr_user_bank.bank_user_name
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    public void setBankUserName(String bankUserName) {
        this.bankUserName = bankUserName;
    }
}