package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.Appeal;

public interface AppealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_appeal
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_appeal
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(Appeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_appeal
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(Appeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_appeal
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    Appeal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_appeal
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(Appeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_appeal
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(Appeal record);
}