package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.AppealLog;

public interface AppealLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_appeal_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_appeal_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(AppealLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_appeal_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(AppealLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_appeal_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    AppealLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_appeal_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(AppealLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_appeal_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(AppealLog record);
}