package com.e3expo.e3.middleware.mapper;

import java.util.List;

import com.e3expo.e3.model.City;

public interface CityMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table dic_city
	 *
	 * @mbggenerated Tue Nov 07 16:26:13 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table dic_city
	 *
	 * @mbggenerated Tue Nov 07 16:26:13 CST 2017
	 */
	int insert(City record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table dic_city
	 *
	 * @mbggenerated Tue Nov 07 16:26:13 CST 2017
	 */
	int insertSelective(City record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table dic_city
	 *
	 * @mbggenerated Tue Nov 07 16:26:13 CST 2017
	 */
	City selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table dic_city
	 *
	 * @mbggenerated Tue Nov 07 16:26:13 CST 2017
	 */
	int updateByPrimaryKeySelective(City record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table dic_city
	 *
	 * @mbggenerated Tue Nov 07 16:26:13 CST 2017
	 */
	int updateByPrimaryKey(City record);
	/**
	 * 查询省份对应的城市信息
	 * @param record
	 * @return
	 */

	List<City> getCityByProvinceId(City record);
}