package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.CompanyConfig;

public interface CompanyConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_company_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_company_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(CompanyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_company_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(CompanyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_company_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    CompanyConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_company_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(CompanyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_company_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(CompanyConfig record);
}