package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.CompanyConfigLog;

public interface CompanyConfigLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_company_config_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_company_config_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(CompanyConfigLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_company_config_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(CompanyConfigLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_company_config_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    CompanyConfigLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_company_config_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(CompanyConfigLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_company_config_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(CompanyConfigLog record);
}