package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.DesignerNeed;

public interface DesignerNeedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_need
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_need
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(DesignerNeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_need
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(DesignerNeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_need
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    DesignerNeed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_need
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(DesignerNeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_need
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(DesignerNeed record);
}