package com.e3expo.e3.middleware.mapper;

import java.util.List;

import com.e3expo.e3.model.DesignerOrder;
import com.e3expo.e3.model.OrderDesignerPrice;
import com.e3expo.e3.model.OrderModel;
import com.e3expo.e3.model.param.OrderParam;
import com.e3expo.e3.model.view.WebAppOrderDesignerView;

public interface DesignerOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_order
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);
    
    /**
     * 查看当前设计师正在进行中的订单的数量
     * @param designerId
     * @return
     */
    int selectCountOrderingDesigner(int designerId);
    
    /**
     * 添加可抢单设计师
     * @param designerOrderList
     */
    void insertDesignerLinkOrder(List<DesignerOrder> designerOrderList);
    
    /**
     * 获取可抢单列表
     * @param param
     * @return List<OrderModel>
     */
    List<OrderModel> selectSingleOrderListByDesignerId(OrderParam param);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_order
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(DesignerOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_order
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(DesignerOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_order
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    DesignerOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_order
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(DesignerOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_order
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(DesignerOrder record);

    /**
     * 根据orderId修改nodeId
     *
     * @param designerOrder
     */
    void updateNodeIdByOrderId(DesignerOrder designerOrder);

    /**
     * 根据OrderId查询designerOrder
     *
     * @param orderId
     * @return
     */
    DesignerOrder selectByOrderId(Integer orderId);

    /**
     * 根据orderID查询指定订单关联设计师的web view
     * @param orderId
     * @return
     */
    WebAppOrderDesignerView selectWebViewByOrderId(Integer orderId);

    /**
     * 查询设计竞标价格
     *
     * @param orderId
     * @return
     */
    List<OrderDesignerPrice> selectDesignerBiddingPrice(Integer orderId);
}