package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.DesignerConfig;

public interface DesignerConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_designer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_designer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(DesignerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_designer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(DesignerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_designer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    DesignerConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_designer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(DesignerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_designer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(DesignerConfig record);
}