package com.e3expo.e3.middleware.mapper;

import java.util.List;

import com.e3expo.e3.model.Designer;
import com.e3expo.e3.model.DesignerConfig;
import com.e3expo.e3.model.DesignerModel;
import com.e3expo.e3.model.User;

public interface DesignerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(Designer record);

    /**
     * 选择性插入字段，如果为空就不插入，并回写主键
     */
    int insertSelective(Designer record);
    
    /**
     * 根据设计师类型查询设计师
     * @param types
     * @return
     */
    List<DesignerModel> selectDesignerByType(Integer[] types);
    
    /**
     * 根据级别查询设计师
     * @param level
     * @return
     */
    List<DesignerModel> selectDesignerByLevel(int level);
    
    /**
     * 查询某级别以上的设计师级别
     * @param level
     * @return
     */
    List<DesignerConfig> selectDesignerLevelUp(int level);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    Designer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(Designer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(Designer record);
    /**
     * 根据userId查询设计师的具体信息
     * @param userId
     * @return
     */
    Designer selectByUserId(Integer userId);
}