package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.ExhibitionAudience;

public interface ExhibitionAudienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_exhibition_audience
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_exhibition_audience
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int insert(ExhibitionAudience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_exhibition_audience
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int insertSelective(ExhibitionAudience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_exhibition_audience
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    ExhibitionAudience selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_exhibition_audience
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int updateByPrimaryKeySelective(ExhibitionAudience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_exhibition_audience
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int updateByPrimaryKey(ExhibitionAudience record);
}