package com.e3expo.e3.middleware.mapper;

import java.util.List;

import com.e3expo.e3.model.OrderNode;

public interface OrderNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_order_node
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_order_node
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(OrderNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_order_node
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(OrderNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_order_node
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    OrderNode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_order_node
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(OrderNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_order_node
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(OrderNode record);
    /**
     * 获取订单节点的所有字典信息
     * @return
     */
    List<OrderNode> getList(String nodeStr);
}