package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.OrderAuditLog;

public interface OrderAuditLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_order_audit_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_order_audit_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(OrderAuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_order_audit_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(OrderAuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_order_audit_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    OrderAuditLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_order_audit_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(OrderAuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_order_audit_log
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(OrderAuditLog record);
}