package com.e3expo.e3.middleware.mapper;

import java.util.Map;

import com.e3expo.e3.model.OsUser;
import com.e3expo.e3.model.param.OsUserParam;

public interface OsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_os_user
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_os_user
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(OsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_os_user
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(OsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_os_user
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    OsUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_os_user
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(OsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_os_user
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(OsUser record);
    OsUser getOsUserByMobileAndPassword(OsUserParam param);
}