package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.PaymentTimerConfig;

public interface PaymentTimerConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_payment_timer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_payment_timer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(PaymentTimerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_payment_timer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(PaymentTimerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_payment_timer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    PaymentTimerConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_payment_timer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(PaymentTimerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_payment_timer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(PaymentTimerConfig record);
}