package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.PaymentType;

public interface PaymentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_payment_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_payment_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(PaymentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_payment_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(PaymentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_payment_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    PaymentType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_payment_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(PaymentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_payment_type
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(PaymentType record);
}