package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.Province;

import java.util.List;

public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_province
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_province
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_province
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_province
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    Province selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_province
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_province
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(Province record);

    /**
     * 查询所有省/市信息列表，列表中每个省/市对象中包含所有的市/区{@code City}的详细信息
     *
     * @return 包含完整市/区信息的所有省/市列表
     */
    List<Province> listProvince();
    /**
     * 根据国家编号查询所有的省份信息
     * @param record
     * @return
     */
    List<Province> getProvincesByCountryId(Province record);

}