package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.RfpDetail;

public interface RfpDetailMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_rfp_detail
     *
     * @mbggenerated Thu Nov 16 13:11:21 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_rfp_detail
     *
     * @mbggenerated Thu Nov 16 13:11:21 CST 2017
     */
    int insert(RfpDetail record);

    /**
     * 单条插入 rfp_detail
     *
     * @param record 详细信息
     * @return 影响条数
     */
    int insertSelective(RfpDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_rfp_detail
     *
     * @mbggenerated Thu Nov 16 13:11:21 CST 2017
     */
    RfpDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_rfp_detail
     *
     * @mbggenerated Thu Nov 16 13:11:21 CST 2017
     */
    int updateByPrimaryKeySelective(RfpDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_rfp_detail
     *
     * @mbggenerated Thu Nov 16 13:11:21 CST 2017
     */
    int updateByPrimaryKey(RfpDetail record);

    /**
     * 使用通过RfpId查询Rfp的详情
     *
     * @param rfpId
     * @return
     */
    RfpDetail selectByRfpId(Integer rfpId);
}
