package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.RfpSpecialDemand;

public interface RfpSpecialDemandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_rfp_special_demand
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_rfp_special_demand
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int insert(RfpSpecialDemand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_rfp_special_demand
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int insertSelective(RfpSpecialDemand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_rfp_special_demand
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    RfpSpecialDemand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_rfp_special_demand
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int updateByPrimaryKeySelective(RfpSpecialDemand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_rfp_special_demand
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int updateByPrimaryKey(RfpSpecialDemand record);
}