package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.RoleFunction;

public interface RoleFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_function
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_function
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(RoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_function
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(RoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_function
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    RoleFunction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_function
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(RoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_role_function
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(RoleFunction record);
}