package com.e3expo.e3.middleware.mapper;

import java.util.List;

import com.e3expo.e3.model.SingleTimerConfig;

public interface SingleTimerConfigMapper {
	
	/**
	 * 获取匹配设计师时间配置
	 * @return
	 */
	SingleTimerConfig selectInfo();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_single_timer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_single_timer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(SingleTimerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_single_timer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(SingleTimerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_single_timer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    SingleTimerConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_single_timer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(SingleTimerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_single_timer_config
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(SingleTimerConfig record);
}