package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.Structure;

public interface StructureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_structure
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_structure
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int insert(Structure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_structure
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int insertSelective(Structure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_structure
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    Structure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_structure
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int updateByPrimaryKeySelective(Structure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_structure
     *
     * @mbggenerated Fri Nov 17 11:34:27 CST 2017
     */
    int updateByPrimaryKey(Structure record);
}