package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.UserInfoFile;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_image
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_image
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(UserInfoFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_image
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(UserInfoFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_image
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    UserInfoFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_image
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(UserInfoFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_designer_image
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(UserInfoFile record);

    /**
     * 批量插入设计师图片
     *
     * @param userInfoFileList 设计师图片列表
     */
    int batchInsert(@Param("userInfoFileList") List<UserInfoFile> userInfoFileList);
    /**
     * 根据UserId获取对应设计师上传的所有图片
     * @param userId 设计师的主键
     * @return
     */
    List<UserInfoFile> selectByUserId(Integer userId);
}