package com.e3expo.e3.middleware.mapper;

import com.e3expo.e3.model.UserBank;

public interface UserBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_bank
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_bank
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insert(UserBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_bank
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int insertSelective(UserBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_bank
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    UserBank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_bank
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKeySelective(UserBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_bank
     *
     * @mbggenerated Tue Nov 07 16:26:13 CST 2017
     */
    int updateByPrimaryKey(UserBank record);
}